In [1]:
# import all the necessery libraries

import pandas as pd
import numpy as np


In [2]:
# read the dataset

df = pd.read_csv('/content/50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.shape

(108, 5)

In [4]:
#checking the null values

df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
# checking the datatype

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
# convert the string type to int type

df['State'] = le.fit_transform(df['State'])

In [8]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [10]:
# split the data(independent & dependent)

x = df.iloc[:,0:-1].values
y= df.iloc[:,4:5].values

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [12]:
xtrain.shape

(75, 4)

In [13]:
xtest.shape

(33, 4)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
# create ANN structure

regressor = Sequential()
regressor.add(Dense(4,activation = 'relu'))
regressor.add(Dense(12,activation = 'relu'))
regressor.add(Dense(9,activation = 'relu'))
regressor.add(Dense(1,activation = 'linear'))

In [16]:
# compiling the ANN model
 
regressor.compile(optimizer = 'adam',loss= 'mse',metrics = ['mse'])

In [17]:
# Training the model
regressor.fit(xtrain,ytrain,batch_size = 10,epochs = 300)


Epoch 1/300
8/8 [==============================] - 1s 3ms/step - loss: 8284895232.0000 - mse: 8284895232.0000
Epoch 2/300
8/8 [==============================] - 0s 2ms/step - loss: 7157356544.0000 - mse: 7157356544.0000
Epoch 3/300
8/8 [==============================] - 0s 2ms/step - loss: 6136969728.0000 - mse: 6136969728.0000
Epoch 4/300
8/8 [==============================] - 0s 3ms/step - loss: 5122008576.0000 - mse: 5122008576.0000
Epoch 5/300
8/8 [==============================] - 0s 2ms/step - loss: 4236983296.0000 - mse: 4236983552.0000
Epoch 6/300
8/8 [==============================] - 0s 2ms/step - loss: 3460922880.0000 - mse: 3460922880.0000
Epoch 7/300
8/8 [==============================] - 0s 2ms/step - loss: 2780190720.0000 - mse: 2780190720.0000
Epoch 8/300
8/8 [==============================] - 0s 2ms/step - loss: 2248968448.0000 - mse: 2248968448.0000
Epoch 9/300
8/8 [==============================] - 0s 2ms/step - loss: 1798385408.0000 - mse: 1798385408.0000
Epoch 10/3

In [20]:
ytest

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77],
       [105733.54],
       [166187.94],
       [ 96778.92],
       [182901.99],
       [105008.31],
       [ 35673.41],
       [ 99937.59],
       [156122.51],
       [ 81005.76],
       [192261.83],
       [191792.06]])

In [21]:
y_pred = regressor.predict(xtest)
y_pred

2/2 [==============================] - 0s 5ms/step


array([[ 43282.535],
       [119764.73 ],
       [ 83325.86 ],
       [178295.61 ],
       [ 91226.88 ],
       [119105.734],
       [129196.82 ],
       [160354.9  ],
       [118188.64 ],
       [ 46224.96 ],
       [106590.39 ],
       [124509.42 ],
       [ 43282.535],
       [132884.38 ],
       [ 72533.625],
       [125541.11 ],
       [125541.11 ],
       [102980.27 ],
       [ 87467.5  ],
       [135074.7  ],
       [144256.61 ],
       [153989.89 ],
       [110453.08 ],
       [162236.58 ],
       [ 93252.89 ],
       [172967.62 ],
       [134937.47 ],
       [ 17976.686],
       [ 88134.57 ],
       [143470.17 ],
       [ 72648.85 ],
       [205028.39 ],
       [201338.83 ]], dtype=float32)

In [23]:
# evaluation

from sklearn.metrics import r2_score

r2_score(ytest,y_pred)*100

86.50941817205249

In [25]:
y_pred.flatten()

array([ 43282.535, 119764.73 ,  83325.86 , 178295.61 ,  91226.88 ,
       119105.734, 129196.82 , 160354.9  , 118188.64 ,  46224.96 ,
       106590.39 , 124509.42 ,  43282.535, 132884.38 ,  72533.625,
       125541.11 , 125541.11 , 102980.27 ,  87467.5  , 135074.7  ,
       144256.61 , 153989.89 , 110453.08 , 162236.58 ,  93252.89 ,
       172967.62 , 134937.47 ,  17976.686,  88134.57 , 143470.17 ,
        72648.85 , 205028.39 , 201338.83 ], dtype=float32)

In [28]:
pd.DataFrame({'Actual value':ytest.flatten(),'Predicted value':y_pred.flatten()}).head(10)

Actual value  Predicted value
0      64926.08     43282.535156
1     146121.95    119764.726562
2      90708.19     83325.859375
3     191050.39    178295.609375
4     108552.04     91226.882812
5     144259.40    119105.734375
6     124266.90    129196.820312
7     155752.60    160354.906250
8     126992.93    118188.640625
9      42559.73     46224.960938

In [29]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [30]:
# 1.Testing with random data

regressor.predict([[1000,12345,45124,0]])

1/1 [==============================] - 0s 78ms/step


array([[12470.734]], dtype=float32)

In [31]:
# testing 2

regressor.predict([[142107.34,91391.77,366168.42,1]])

1/1 [==============================] - 0s 50ms/step


array([[162236.58]], dtype=float32)

In [32]:
# testing 3

regressor.predict([[153441.51,101145.55,407934.54,1]])

1/1 [==============================] - 0s 68ms/step


array([[178295.61]], dtype=float32)