In [1]:
import numpy as np

In [ ]:
## Create an array


a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
a.ndim

NameError: ignored

In [ ]:
# create two dimensional array

dim2 = np.array([[1,2,3],[5,6,7]])


In [ ]:
dim2.ndim

2

In [ ]:
# create three dimensional array

dim3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])



In [ ]:
dim3.ndim

3

## Zero's and one's

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# create a 3 dimensional array with 4 rows and 5 columns, all elements should be 1

In [ ]:
q=np.ones([3,4,5])
q

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
q.ndim

3

## functions

In [ ]:
arr=np.array([22,23,250,78])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.argmax() #max value in index position

2

In [ ]:
arr.argmin() #min value in index position

0

In [ ]:
arr[1]

23

In [ ]:
arr

array([ 22,  23, 250,  78])

In [ ]:
arr[1:]

array([ 23, 250,  78])

In [ ]:
arr[:3]

array([ 22,  23, 250])

In [ ]:
arr[0:-1]

array([ 22,  23, 250])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1=np.array([1,2,3.3,5,6,7,8,9])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr1.size

8

In [ ]:
## create a numpy array with size 5, of datatype float

In [ ]:
arr1=np.array([1,2.0,3,4,5])


In [ ]:
arr1.size

6

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
# Create a two dim array
# four arrays in the external array
# it should have two elements each

In [ ]:
np.array([[1,2],[3,4],[5,6],[7,8]])


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.array([[1,2],[3,4],[5,6],[7,8]]).ndim


2

## Resize and reshape

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(12).ndim

1

In [ ]:
s=np.arange(12).reshape(3,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
s.shape

(3, 4)

In [ ]:
s.max()

11

In [ ]:
s.min()

0

In [ ]:
x=np.array([1,2,3,4])

In [ ]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
s.shape

(3, 4)

## Transpose

In [ ]:
w=s.T
w

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
w.shape

(4, 3)

## Floor and ceil


In [ ]:
a=np.array([12,2.3,4,5.2,7])
a

array([12. ,  2.3,  4. ,  5.2,  7. ])

In [ ]:
np.floor(a)

array([12.,  2.,  4.,  5.,  7.])

In [ ]:
np.ceil(a)    # it is giving the next integer value

array([12.,  3.,  4.,  6.,  7.])